POST https://localhost:2113/streams/secure_stream
Content-Type: application/vnd.eventstore.events+json
Authorization: Basic nonaudit:Password


[
  {
    "eventId": "fbf4a1a3-b4a4-4dfe-a01f-ec52c34e19e9",
    "eventType": "event-type",
    "data": {
      "a": "1"
    }
  }
]


