POST https://localhost:2113/streams/newstream
Content-Type: application/vnd.eventstore.events+json
Authorization: Basic admin:changeit


[
  {
    "eventId": "fbf4a1a3-b4a3-3dfe-a01f-ec52c34e19e9",
    "eventType": "event-type",
    "data": {
      "a": "1"
    }
  }
]

###
# Test EventStore 24.10.0.1384 passed
#
####
