GET http://127.0.0.1:2113/streams/newstream?embed=rich
Accept:application/vnd.eventstore.atom+json






###
# 
# PASSED Eventstore 23.10 
# debug steps, make sure the stream exists
# 01_ESDB_event_post.http will add events
# to this stream
# PASSED Event Store 24.10.0.1384 
#### 
